// Compiles the kids' track (packages/content/kids/<door>.json) into generated/kids.js, which the app bundles.
// Review notes and the review block stay behind. A door whose file fails the check is left out (and the build exits 1).
//   node packages/content/scripts/build-kids.mjs [--check]     (--check: fail if generated/kids.js is out of date)
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { DOOR_KEYS } from "../src/lesson-script.js";

// checkKids lives in src/kids.js, which imports generated/kids.js; make sure that file exists before importing it.
const OUT = new URL("../generated/kids.js", import.meta.url);
if (!existsSync(OUT)) writeFileSync(OUT, "export default {};\n");
const { checkKids, compileKids } = await import("../src/kids.js");

const out = {};
let failed = 0;
for (const door of DOOR_KEYS) {
  const url = new URL(`../kids/${door.toLowerCase()}.json`, import.meta.url);
  if (!existsSync(url)) continue;
  const file = JSON.parse(readFileSync(url, "utf8"));
  const { errors } = checkKids(file, door);
  if (errors.length) { console.log(`${door}: left out (${errors.length} error(s); run validate-kids.mjs)`); failed++; continue; }
  out[door] = compileKids(file);
}
const body = `// Generated by packages/content/scripts/build-kids.mjs from packages/content/kids/*.json. Do not edit by hand.\n// Every lesson here is a DRAFT pending Keeper review.\nexport default ${JSON.stringify(out)};\n`;
if (process.argv.includes("--check")) {
  const now = readFileSync(OUT, "utf8");
  if (now !== body) { console.log("generated/kids.js is out of date: run node packages/content/scripts/build-kids.mjs"); process.exit(1); }
  console.log(`generated/kids.js is up to date (${Object.keys(out).length} doors)`);
} else {
  writeFileSync(OUT, body);
  console.log(`wrote generated/kids.js: ${Object.keys(out).map((d) => `${d} ${out[d].lessons.length}`).join(" · ") || "no doors"}`);
}
process.exit(failed ? 1 : 0);
