// Turns each path's five-year plan (docs/curriculum/<door>/y1.md … y5.md) into generated/outline-<door>.js:
// one entry per session, days 22–1791. Every day is its own numbered line:
//   22. **title** · word or — · hook · practice · *carry*
// Headings: "# " = the camp or year, "## " = the part (week or block), "### " = a sub-part.
// These are DRAFT OUTLINES, not scripts — every line waits on that tradition's Keeper.
//   node packages/content/scripts/import-paths.mjs [--check]     (--check: report gaps, write nothing)
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..", "..");
const DOORS = ["CHRISTIANITY", "CATHOLIC", "JUDAISM", "ISLAM", "BUDDHISM", "SIKHISM", "SPIRITUAL"];
const FIRST = 22, LAST = 1791;
const YEAR_OF = (d) => (d <= 331 ? 1 : 2 + Math.floor((d - 332) / 365));
const clean = (s) => s.replace(/\*\*/g, "").replace(/\s+/g, " ").trim();
const check = process.argv.includes("--check");
const only = process.argv.find((a) => DOORS.includes(a));

function parse(md, sessions, file) {
  let camp = null, part = null, sub = null;
  const dupes = [];
  for (const raw of md.replace(/\r/g, "").split("\n")) {
    const line = raw.trim();
    const h = line.match(/^(#{1,3}) (.+)$/);
    if (h) { const t = clean(h[2]); if (h[1] === "#") { camp = t; part = sub = null; } else if (h[1] === "##") { part = t; sub = null; } else sub = t; continue; }
    const m = line.match(/^(\d+)\.\s+(.+)$/);
    if (!m) continue;
    const day = Number(m[1]);
    if (day < FIRST || day > LAST) continue;
    const parts = m[2].split(" · ").map((p) => p.trim());
    const carry = parts.length > 1 && /^\*[^*].*\*$/.test(parts[parts.length - 1]) ? parts.pop().replace(/^\*|\*$/g, "").trim() : null;
    const [title, word, hook, practice] = parts;
    if (sessions.has(day)) dupes.push(day);
    sessions.set(day, {
      day, year: YEAR_OF(day), camp, part: sub ? `${part} · ${sub}` : part,
      title: clean(title || ""), word: word && !/^[—–-]$/.test(word) ? clean(word) : null,
      hook: hook ? clean(hook) : null, practice: practice ? clean(practice) : null,
      carry: carry && carry.replace(/(^|\s)i(?=[\s'’,.!?]|$)/g, "$1I"), // carries are lowercase, but "i" reads as a typo
    });
  }
  if (dupes.length) console.log(`  ${file}: days listed twice: ${dupes.slice(0, 10).join(", ")}${dupes.length > 10 ? "…" : ""}`);
}

for (const door of only ? [only] : DOORS) {
  const dir = join(root, "docs", "curriculum", door.toLowerCase());
  const sessions = new Map();
  for (const f of ["y1.md", "y2.md", "y3.md", "y4.md", "y5.md"]) if (existsSync(join(dir, f))) parse(readFileSync(join(dir, f), "utf8"), sessions, `${door}/${f}`);
  const gaps = [];
  for (let d = FIRST; d <= LAST; d++) if (!sessions.has(d)) gaps.push(d);
  const thin = [...sessions.values()].filter((s) => !s.title || !s.carry).map((s) => s.day);
  console.log(`${door}: ${sessions.size} sessions${gaps.length ? `, MISSING ${gaps.length} (${gaps.slice(0, 15).join(",")}${gaps.length > 15 ? "…" : ""})` : ", none missing"}${thin.length ? `, ${thin.length} without a title or carry (${thin.slice(0, 10).join(",")})` : ""}`);
  if (check || !sessions.size) continue;
  // index fixes: a day's word or carry corrected over the plan (docs/curriculum/index-fixes/<door>.json, {day: {word, carry}})
  const fixFile = join(root, "docs", "curriculum", "index-fixes", `${door.toLowerCase()}.json`);
  if (existsSync(fixFile)) for (const [day, fix] of Object.entries(JSON.parse(readFileSync(fixFile, "utf8")))) { const s = sessions.get(Number(day)); if (s) Object.assign(s, fix); }
  const list = [...sessions.values()].sort((a, b) => a.day - b.day);
  writeFileSync(join(here, "..", "generated", `outline-${door.toLowerCase()}.js`),
    `// GENERATED by packages/content/scripts/import-paths.mjs from docs/curriculum/${door.toLowerCase()}/*.md — do not edit by hand.\n// ${door}, days ${FIRST}–${LAST}: DRAFT OUTLINES (title, hook, practice, carry), not scripts. Not Keeper-reviewed.\nexport default ${JSON.stringify({ door, status: "outline-draft", sessions: list })};\n`);
}
