// Camp one's guess ("<word> — what do you think it means?"): one right, specific answer and wrong ones that are
// plausible but plainly wrong (owner, 2026-09-30).
//
// The design build answered the guess with the day's carry line ("Father → you're not addressing a stranger",
// "al-Fatiha → in the name of the merciful"), and drew the wrong answers from other days' carry lines, so the "answer"
// was a slogan and sometimes none of the choices was what the word means. A script day now answers from the script's
// own gloss (index.js: guessFor); this table covers the days where that gloss is missing, or where the script's
// match pairs made a second answer true ("grace" → "a gift, a favor, freely given"), and the days with no script yet.
//
// Each entry: [right answer, wrong, wrong, (wrong)]. The right answer is taken from that day's own lesson text (the
// script's "what it means" and "the word", or the design's hook and word line); nothing here teaches something new.
// A table entry wins over the script, so when a script is rewritten, check its entry still agrees.
export const QUIZ = Object.freeze({
  CHRISTIANITY: {
    2: ["a gift you didn't earn, from the Greek charis", "the prayer before dinner", "a reward for being good"],
    8: ["a request for rescue: pull us clear", "the grand ending: kingdom, power, glory, amen", "a test, a trial, a temptation"],
    13: ["in Greek, agape: love that's a choice, not a mood", "love is the warm feeling from the wedding reading", "the love that wants"],
    14: ["rome's execution, turned into the most recognized sign on earth", "a piece of jewelry, a shape on a steeple", "the Roman governor who sentenced him"],
    3: ["a builder's son from a small town, who ate with the people others avoided", "the face in the stained-glass window", "a king raised in a palace"],
    11: ["the one who wasted everything, and the father who ran to meet him anyway", "a story about a bad son who learned his lesson", "a parable about saving money"],
    18: ["kol demamah dakah: a sound of thin silence", "god speaks in the big moments — the storm, the sign, the fire", "a vow never to speak"],
    4: ["the family word for God — and our, not my", "a formal way to open a prayer", "a title only priests may use", "the first of the Ten Commandments"],
    5: ["a reign — God's way of running things, coming here", "a place you go after you die", "a country with a king and borders"],
    6: ["enough for today, for all of us, like manna in the desert", "just food, nothing more", "a year's supply, stored up safely"],
    7: ["letting go of what's owed, both ways", "saying sorry to God", "pretending it never happened"],
    9: ["shabbat: a day to stop, made for people, given to everyone", "an old rule about not working on Sundays", "a church service you have to attend"],
    10: ["a story that flips the question: not who counts as my neighbor, but who acted like one", "a nice man who helps strangers", "a rule about who counts as your neighbor"],
    12: ["eight blessings that start at the bottom and turn the ladder upside down", "nice sayings for a greeting card", "ten rules carved in stone"],
    15: ["pascha: the morning the stone was moved and the tomb was empty", "eggs, bunnies, a spring holiday", "the day Jesus was born"],
    16: ["a hundred and fifty songs, with praise and complaint side by side", "calm, pious poems for quiet moments", "the laws of Moses, written as a list"],
    17: ["pistis: not certainty: trust, even the size of a seed", "being certain, with no doubts", "believing things for no reason at all"],
    19: ["sharing one loaf and one cup", "a small bit of bread and a sip in church", "a private prayer said alone"],
    20: ["ekklesia: not a building: the called-out ones, gathered", "a building with a steeple", "the clergy, not the people"],
    21: ["the beginning of the gospel", "a chapter-and-verse number", "the last line of the Bible"],
  },
  CATHOLIC: {
    12: ["saying it out loud to another person, and hearing out loud that you're forgiven", "a dark booth where someone judges you", "a prayer or act to make things right"],
    2: ["a two-second prayer that traces the cross over all of you and names the Trinity", "a good-luck gesture before a game", "a salute to the priest"],
    3: ["the good news: the reading about the life of Jesus that everyone stands to hear", "the sermon after the readings", "a reading from the Old Testament"],
    4: ["turning to whoever is beside you, just before the table, to say peace be with you", "a friendly pause so people can say hi", "the priest's blessing at the end of Mass"],
    5: ["thanksgiving: bread and wine, the words of the Last Supper, and communion", "the collection taken during Mass", "a prayer said before any meal"],
    6: ["a young woman who asked a question and then said yes, the yes the whole story turns on", "a statue of a calm woman in blue", "the first of the apostles"],
    7: ["flawed people who kept going, still one family with the living", "perfect people carved in plaster", "angels who were never human"],
    8: ["francis of Assisi, the rich kid who gave it all back and went toward the outcasts", "the saint with the birds on the garden statue", "a monk who lived alone in the desert"],
    9: ["every flame has a job: Christ's light, his presence, or someone's prayer", "church decoration, or old lighting", "a way to pay for a prayer"],
    10: ["a loop of five decades that keeps count, so the hands are busy and the heart is free", "a Catholic necklace, or a lucky charm", "a list of saints to memorize"],
    11: ["an angel's hello and a cousin's blessing from Luke, then the Church's request: pray for us", "a fast prayer, or a desperate football pass", "a prayer that replaces talking to God"],
    13: ["one day held open, so the gift of rest and worship actually gets opened", "an obligation to sit through church", "the seventh day, the Sabbath"],
    14: ["the prayer Jesus taught, opening with a family word, and with no I or me in it anywhere", "the prayer everyone memorizes as kids", "a prayer to Mary"],
    15: ["forty days of prayer, fasting and giving, where less becomes a way of paying attention", "six weeks of giving up chocolate", "the forty days after Easter"],
    16: ["the feast of the resurrection, the empty tomb, and the women who were sent to tell", "eggs, bunnies, a spring holiday", "the day Jesus was born"],
    17: ["the bread and wine Catholics believe become Christ's body and blood", "church people eat a wafer as a symbol", "a blessing said over the congregation"],
    18: ["the small-c word means universal, for everyone, everywhere", "catholic is just the name of one denomination", "a building with a steeple"],
    19: ["a funny, blunt woman who struggled with prayer for years, then described it as friendship", "a stern nun in a painting", "the nun who founded the Missionaries of Charity"],
    20: ["misericordia: a heart that goes out to someone in trouble, received first, then given away", "letting someone off the hook", "a feeling you keep to yourself"],
    21: ["one hundred and fifty praises, laments and songs, the prayer book Jesus himself prayed", "old church hymns", "the laws of Moses"],
  },
  JUDAISM: {
    9: ["the heel-grabber who wrestled until dawn, came away limping, and was renamed Israel", "a wrestling match in an old story", "the brother who sold his birthright for stew"],
    5: ["a blessing, said to the source before you eat, and after you're full", "a festive bread for Shabbat", "a prayer only rabbis say"],
    10: ["giving as justice, the poor person's share, not a favor", "charity, when you feel like it", "a tax paid to the Temple"],
    21: ["this week's portion, one of fifty-four, read by a whole people in step", "a reading assignment", "a prayer for the new moon"],
    2: ["six words that begin hear, O Israel, said morning and night with the eyes covered", "a blessing said over wine", "the Ten Commandments, recited"],
    3: ["to stop: the seventh day, Friday sunset to Saturday stars, a rest for everyone", "the Jewish day of worship", "a fast day once a year"],
    4: ["two flames lit before sunset on Friday, remember and observe, for peace in the home", "candles to make dinner look nice", "a memorial for the dead"],
    6: ["a chapter built on a refrain: God makes, then looks, and calls it good", "the story of Adam and Eve's garden", "the flood and Noah's ark"],
    7: ["remember, and observe: rest, for you, your household, the stranger and even the animals", "a rule about going to worship", "a rule for priests only"],
    8: ["father of many nations, and the first in the Torah to argue with God for strangers", "an old man in the Bible", "the one who led the people out of Egypt"],
    11: ["the story Judaism returns to most, retold every year in the first person: we were slaves", "an old story about Moses and a sea", "the first book of the Torah"],
    12: ["the mountain of the covenant, where the people answered: we will do, and we will hear", "the hill where the Temple stood in Jerusalem", "the river the people crossed into the land"],
    13: ["ten sayings spoken to a people, starting not with a rule but with who is speaking", "ten rules carved in stone", "ten plagues sent on Egypt"],
    14: ["intention: aiming your heart where your words and actions are going", "meaning well", "a prayer said very fast"],
    15: ["making yourself alone, to talk to God out loud in your own words", "some kind of meditation", "praying only in Hebrew, from a book"],
    16: ["the day of atonement: twenty-five hours of fasting, confessing together, and closing gates", "the Jewish new year", "a harvest festival in huts"],
    17: ["return: not shame, but turning around, and answering the call home", "repentance, and feeling bad", "a blessing before a meal"],
    18: ["a count of ten, the smallest community, so some prayers are never said alone", "a prayer book", "the rabbi's assistant"],
    19: ["the doorpost, and the handwritten words of the Shema rolled up and fixed there", "a Jewish decoration on the door", "a prayer shawl"],
    20: ["teaching: a handwritten scroll, read from end back to beginning, year after year", "the scribe who writes it by hand", "a book of laws about food"],
  },
  ISLAM: {
    2: ["in the name of God", "a Muslim grace before meals", "a greeting: peace be with you"],
    3: ["the praise belongs to God", "may God forgive me", "God is the greatest"],
    4: ["if God wills", "maybe, or probably not", "glory be to God"],
    5: ["witness, prayer, giving, fasting, pilgrimage", "five rules to tick off", "the five daily prayers"],
    6: ["the opening: seven verses said in every unit of every prayer", "the last chapter of the Qur'an", "the call to prayer from a minaret"],
    7: ["lord: the one who owns, raises and looks after, here the Lord of all the worlds", "a title, like a king's, and nothing more", "a prophet sent to one people"],
    8: ["mercy, from the root of the womb, named twice in a row: ar-Rahman, ar-Rahim", "mercy means letting someone off", "judgment, weighed out exactly"],
    9: ["the Day of Judgment, the day every account is settled, held by the one just named merciful", "the scary verse in the middle", "the day of the week for gathering"],
    10: ["the oneness of God, affirmed: You alone we worship, You alone we ask for help", "the pilgrimage to Mecca", "a night prayer said alone"],
    11: ["the straight path: the road al-Fatiha asks to be shown, seventeen times a day", "a strict, narrow line you mustn't step off", "the direction of prayer, toward Mecca"],
    12: ["o God, answer this: the word said when al-Fatiha ends, the seven verses complete", "a way to say \"the end.\"", "peace be upon him"],
    13: ["the washing before prayer: hands, mouth, face, arms, head and feet", "washing your hands before praying, like manners", "clean earth, when there's no water"],
    14: ["the prayer in its set shape: five times a day, standing, bowing, forehead to the ground", "prayer is talking to God in words", "a charity given once a year"],
    15: ["the call to prayer, from the root for ear", "a song from a minaret", "the Friday sermon"],
    16: ["friday, gathering day: a sermon and a prayer at noon, then back to work", "the Muslim day off", "the feast at the end of Ramadan"],
    17: ["remembrance: short words of praise, said again and again", "repeating words like a chant", "a sermon given on Friday"],
    18: ["the month of fasting, dawn to sunset, when the Qur'an was first revealed", "a month when Muslims don't eat at all", "the month of the pilgrimage to Mecca"],
    19: ["two and a half percent of savings, given once a year, from a root meaning to purify", "a religious tax paid to the state", "giving from the heart, any amount"],
    20: ["for Muslims the last messenger of God, called al-Amin, the trustworthy", "the founder of a religion", "the angel who brought the Qur'an"],
    21: ["the thirtieth part of the Qur'an, the short surahs, where nearly everyone begins", "the first chapter, said in every prayer", "a book of the Prophet's sayings"],
  },
  BUDDHISM: {
    16: ["compassion: metta when it meets pain, the heart that trembles and stays beside, not above", "feeling sorry for people", "pity, which looks down"],
    11: ["impermanence, the first of the three marks", "permanent, lasting", "a soul that never dies"],
    2: ["the first meditation object, always with you, always now", "breathing exercises", "holding your breath as long as you can"],
    3: ["not only suffering: the wobble in the wheel, the itch under things", "a ball of bad luck from a past life", "the peace at the end of the path"],
    4: ["not a name but a title: the one who woke up", "the Buddha is the god of Buddhism", "a statue for good fortune"],
    5: ["there is dukkha", "buddhists are pessimists", "everyone is happy underneath"],
    6: ["dukkha comes from tanha, a grasping thirst for things to be other than they are", "buddhists aren't supposed to want anything", "life is suffering, full stop"],
    7: ["the third noble truth, nirodha: when the thirst ends, dukkha ends", "nirvana is Buddhist heaven", "the way the wheel keeps turning"],
    8: ["eight parts of one path, wisdom, conduct and meditation, practiced together for a life", "eight rules to follow", "the four stages of a monk's life"],
    9: ["mindfulness, but older and fuller: remembering to notice, the gatekeeper at the gate", "a relaxation technique", "emptying the mind of all thought"],
    10: ["a sound that begins and fades, calling the mind into the present and holding the time", "a timer with better branding", "a call to come and eat"],
    12: ["not-self, the third mark: nothing in the five heaps can be held as me, mine, or my self", "buddhists say you don't exist", "a soul that moves from life to life"],
    13: ["five training rules, taken on freely, that give everyone around you freedom from fear", "commandments handed down from a god", "rules only monks keep"],
    14: ["generosity as the first practice, the open hand that makes the rest of the path possible", "donating to charity", "giving up everything you own"],
    15: ["slow, on purpose, going nowhere, feeling each step, so the calm can come with you", "going for a mindful stroll", "walking fast to clear your head"],
    17: ["the community, the third jewel: the people who practice together", "a temple building", "the Buddha's teaching"],
    18: ["birth stories: the Buddha's past lives, many as animals, showing the path from the inside", "buddhist fables for kids", "the Buddha's final words"],
    19: ["upekkha: looking on from a steady place, a rock in the eight winds", "staying calm by not caring", "a kind of trance"],
    20: ["the path between chasing pleasure and punishing the body, found by tuning, again and again", "don't do anything too much", "halfway between two religions"],
    21: ["423 verses of the Buddha's teaching, beginning with the mind", "the Buddha's life story", "rules for monks and nuns"],
  },
  SPIRITUAL: {
    2: ["the simplest instruction there is, and somehow one of the hardest", "sit still until your mind is empty", "a pose you need to be flexible for"],
    3: ["to see what's already here, and to see where your mind just went", "to judge what you see", "to stop all your thoughts"],
    4: ["use what you'd want as the map for what you give", "be nice", "treat people the way they treat you"],
    5: ["a line in time, a sound people share, a sound that fades into silence", "a timer", "a signal that you did it right"],
    6: ["the first place so many paths ask you to notice, and the easiest one to come back to", "the thing that carries your head around", "something to ignore while you sit"],
    7: ["things that happen in you, like weather", "the voice in your head, which is you", "problems to be stopped"],
    // days 8–21: no script yet; the answer comes from the day's hook
    8: ["being good to people, starting with the person in the mirror", "being nice so people like you", "never saying no"],
    9: ["noticing what's good and saying thank you, even on a hard day", "owing someone a favor", "pretending everything is fine"],
    10: ["the quiet that every tradition's mystics agree on", "not being allowed to speak", "an empty, awkward pause"],
    11: ["the hour to stop: every culture stopped at dusk", "a god to worship", "a reason to get up early"],
    12: ["we're all just walking each other home", "exercise to hit a step count", "getting somewhere fast"],
    13: ["doing something for someone, with no receipt", "a job you're paid for", "helping so you get thanked"],
    14: ["you get one life and it ends; the Stoics kept that close", "something never to think about", "the idea that time is endless"],
    15: ["what is aware right now: the looker behind the looking", "knowing a lot of facts", "being on high alert"],
    16: ["the thing you check 144 times a day; putting it face down is a practice", "a tool never to put down", "something to throw away"],
    17: ["a feeling you're far from the only one to have", "something only you feel", "the same as being alone"],
    18: ["those who know they have enough are rich", "settling for less than you deserve", "having everything you want"],
    19: ["the feeling of looking at something bigger than you", "fear of getting in trouble", "being impressed by someone famous"],
    20: ["you can't do this alone: find your people", "a business you work for", "a crowd you don't know"],
    21: ["a Persian poet, and a field beyond our ideas of right and wrong", "a Greek philosopher", "a Roman emperor who wrote about calm"],
  },
  // no scripts yet: the answer is the design's own "the word" line
  HINDUISM: {
    2: ["one sound for everything, and the silence underneath", "a hum to relax your jaw", "a greeting to an elder"],
    // week one rebuilt 2026-10-06: Ganesha, om, Gayatri, namaste, arti, ishta devata, karma; dharma moves to 9, shanti to 14
    3: ["a prayer that the light wake up our minds", "a prayer for wealth and luck", "a song to end a puja"],
    4: ["I bow to you", "hello, in Sanskrit", "peace be with you"],
    5: ["the offering of light, passed to everyone", "a painting of a god", "the morning bath"],
    6: ["the form of God that feels like yours", "a god of good luck", "a family's oldest temple"],
    7: ["action, and what it grows: not payback", "cosmic payback", "fate you can't change"],
    8: ["attention, offered", "a feast day", "a list of rules for the temple"],
    9: ["the thing that's yours to hold: not rules, not just duty", "a list of rules to obey", "the result of what you do"],
    10: ["the self behind your eyes, the one who's been here all along", "your personality", "the spirit of an ancestor"],
    11: ["the whole: the ocean the wave forgets it is", "one god among many", "a heaven you go to"],
    12: ["the one who removes the dark", "a celebrity expert", "someone you must obey"],
    13: ["counted repetition: the hand keeps count, the mind gets to rest", "a day of fasting", "a song sung in a group"],
    14: ["peace, in three directions, and the third one is yours", "strength", "a morning prayer"],
    15: ["service with the self out of the way", "a donation for a blessing", "a vow of silence"],
    16: ["love, practiced like an instrument", "strict discipline of the body", "study of old texts"],
    17: ["not adding harm: the courage not to strike", "never eating after sunset", "being too polite to say no"],
    18: ["the gap between what it looks like and what it is", "a goddess of wealth", "the cycle of rebirth"],
    19: ["freedom: the knot untied", "a reward in heaven", "a pilgrimage"],
    20: ["good company: the room that keeps you true", "a sacred bath", "a retreat alone"],
    21: ["the song: Krishna's counsel to Arjuna before the battle", "a book of Hindu laws", "a collection of hymns to the sun"],
  },
  SIKHISM: {
    2: ["wonder + teacher: the word Sikhs say for God", "a greeting between friends", "the first Sikh Guru"],
    3: ["the first Sikh Guru, who walked for twenty years", "the tenth Guru, who formed the Khalsa", "the city of the Golden Temple"],
    4: ["one creator: the first symbol of the scripture", "the five Ks", "the Sikh flag"],
    5: ["one creator, truth is the name", "without fear, without hate", "the morning prayer, sung in full"],
    6: ["without fear, without hate", "one creator, truth is the name", "rising in high spirits"],
    7: ["remembrance: the name on the breath", "a sacred bath", "a silent fast"],
    8: ["the free kitchen: everyone on the floor, everyone the same meal", "the cloth of a turban", "a prayer at sunset"],
    9: ["honest work, the first of Nanak's three pillars", "sharing what you earn", "remembering the name"],
    10: ["share what you earn, the second pillar", "honest work", "remembering the name"],
    11: ["remember the name, the third pillar", "honest work", "sharing what you earn"],
    12: ["a crown you tie yourself", "a sign of rank in an army", "a hat for cold weather"],
    13: ["the congregation, the company you keep", "the free kitchen", "a retreat alone"],
    14: ["the door of the Guru, open to anyone", "a Sikh school", "the Guru's birthplace"],
    15: ["ever-rising spirits: optimism as a discipline", "a warrior's sword", "a morning bath"],
    16: ["five things a Sikh carries: reminders you can touch", "five daily prayers", "five rules for the kitchen"],
    17: ["the tenth Guru, who formed the Khalsa: the saint-soldier", "the first Guru, who walked for twenty years", "the builder of the Golden Temple"],
    18: ["stories of the Gurus", "the Sikh morning prayer", "songs sung at a wedding"],
    19: ["the standing prayer, for the good of all", "the free kitchen", "a wedding hymn"],
    20: ["the scripture that is the Guru: a living book", "a history of the Sikh kings", "the tenth Guru"],
    21: ["Nanak's morning prayer, 38 stanzas", "the evening prayer at the Golden Temple", "the story of the five Ks"],
  },
});
