// Builds packages/content/src/week1-data.js from the rebuilt first weeks (owner, 2026-10-06): one file per path in
// docs/learning/week1/<DOOR>.json plus that path's scripts for days 1–21. The app reads the result at load:
//   WEEK_INDEX  the camp-one index (title, word, carry, length, the outline fallback) for days 1–21, in the new order
//   CHECKIN     the seven week-one questions (look-backs from day 3, the day-7 check-in)
//   QUIZ        the "what do you think it means?" answers for days 2–21: [right, wrong, wrong]
//   BET         day one's opening question (word, options, answer, reveal)
//   SAY_IT      extra tap-to-hear words
//   node scripts/learning/build-week1.mjs [--check]
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../../", import.meta.url));
const DIR = `${root}docs/learning/week1`;
const OUT = `${root}packages/content/src/week1-data.js`;
const script = (door, d) => JSON.parse(readFileSync(`${root}docs/curriculum/${door.toLowerCase()}/scripts/y1/day-${String(d).padStart(4, "0")}.json`, "utf8"));
const problems = [];
const out = { WEEK_INDEX: {}, CHECKIN: {}, QUIZ: {}, BET: {}, SAY_IT: {} };
for (const f of existsSync(DIR) ? readdirSync(DIR).filter((x) => /^[A-Z]+\.json$/.test(x)) : []) {
  const spec = JSON.parse(readFileSync(`${DIR}/${f}`, "utf8"));
  const door = spec.door;
  out.WEEK_INDEX[door] = {};
  for (let d = 1; d <= 21; d++) {
    const s = script(door, d);
    if (s.day !== d) problems.push(`${door} day ${d}: script says day ${s.day}`);
    out.WEEK_INDEX[door][d] = { day: d, title: s.title, word: s.word, hook: s.hook, length: s.length, carry: s.carry, segments: s.segments.map((g) => ({ type: g.type, duration: g.duration, voice: g.voice, screen: g.screen })) };
  }
  const ck = spec.checkin || [];
  if (ck.length !== 7) problems.push(`${door}: checkin needs 7 questions`);
  ck.forEach((q, k) => {
    if (q.day !== k + 1) problems.push(`${door} checkin ${k + 1}: day ${q.day}`);
    if (!Array.isArray(q.options) || q.options.length !== 3 || q.answer !== 0) problems.push(`${door} checkin ${k + 1}: 3 options, the right one first (answer 0)`);
    if (q.word !== out.WEEK_INDEX[door][k + 1].word) problems.push(`${door} checkin ${k + 1}: word "${q.word}" isn't day ${k + 1}'s word "${out.WEEK_INDEX[door][k + 1].word}"`);
  });
  out.CHECKIN[door] = ck;
  for (const [d, a] of Object.entries(spec.quiz || {})) if (!Array.isArray(a) || a.length !== 3) problems.push(`${door} quiz ${d}: [right, wrong, wrong]`);
  out.QUIZ[door] = spec.quiz || {};
  if (spec.bet) {
    const b = spec.bet;
    if (!b.options?.includes(b.answer)) problems.push(`${door} bet: the answer must be one of the options`);
    if (b.word !== out.WEEK_INDEX[door][1].word) problems.push(`${door} bet: word "${b.word}" isn't day 1's word`);
    out.BET[door] = b;
  }
  out.SAY_IT[door] = spec.sayIt || {};
}
if (problems.length) { console.log(problems.join("\n")); process.exitCode = 1; }
if (!process.argv.includes("--check") && !problems.length) {
  writeFileSync(OUT, `// GENERATED by scripts/learning/build-week1.mjs from docs/learning/week1/*.json and days 1–21 of each path's scripts.\n// Do not edit by hand.\n${Object.entries(out).map(([k, v]) => `export const ${k} = ${JSON.stringify(v)};`).join("\n")}\n`);
  console.log(`week1-data.js: ${Object.keys(out.WEEK_INDEX).join(", ") || "no paths yet"}`);
}
