// Builds apps/app/src/content/placement-curated.ts from the hand-checked question bank (docs/learning/bank/<door>/
// stop-NN.json; rules in docs/learning/QUESTION_RULES.md). Only multiple-choice items ship to the placement check; the
// open-answer ("explain") items wait for the short-answer check. A door with a curated bank uses it in place of the
// lesson-generated questions (apps/app/src/content/placement.ts).
//   node scripts/learning/build-curated.mjs
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../../", import.meta.url));
const BANK = `${root}docs/learning/bank`;
const OUT = `${root}apps/app/src/content/placement-curated.ts`;
const out = {};
for (const dir of readdirSync(BANK)) {
  const files = readdirSync(`${BANK}/${dir}`).filter((f) => /^stop-\d+\.json$/.test(f)).sort();
  if (!files.length) continue;
  const stops = [];
  for (const f of files) {
    const items = JSON.parse(readFileSync(`${BANK}/${dir}/${f}`, "utf8")).filter((x) => x.kind === "choice" && x.status !== "retired");
    const n = Number(f.match(/\d+/)[0]);
    stops[n] = items.map((x) => ({ id: x.id, day: x.day, d: x.difficulty, q: x.stem, o: x.options, a: x.answer, ...(x.es ? { es: { q: x.es.stem, o: x.es.options } } : {}) }));
  }
  out[dir.toUpperCase()] = stops;
}
const statuses = [...new Set(readdirSync(BANK).flatMap((d) => existsSync(`${BANK}/${d}`) ? readdirSync(`${BANK}/${d}`).filter((f) => f.endsWith(".json")).flatMap((f) => JSON.parse(readFileSync(`${BANK}/${d}/${f}`, "utf8")).map((x) => x.status)) : []))];
const body = `// GENERATED by scripts/learning/build-curated.mjs from docs/learning/bank. Do not edit by hand.
// The hand-written placement questions (docs/learning/QUESTION_RULES.md): blind-solved and form-checked; item status
// ${statuses.join(", ")} (Keeper review pending before any public release). One list of choice items per stop.
export type CuratedQ = { id: string; day: number; d: number; q: string; o: string[]; a: number; es?: { q: string; o: string[] } };
export const CURATED: Readonly<Record<string, CuratedQ[][]>> = ${JSON.stringify(out)};
`;
writeFileSync(OUT, body);
console.log(Object.entries(out).map(([k, v]) => `${k}: ${v.length} stops, ${v.flat().length} questions`).join("\n"));
