// GENERATED by packages/content/scripts/build-placement.mjs from the lesson scripts. Do not edit by hand: change the
// lessons (docs/curriculum) or the script, then run it again.
// DRAFT — NOT KEEPER-REVIEWED: every question is a lesson's own game item, and the lessons are pending Keeper review
// (docs/CONTENT_RELEASE.md). The adaptive "where are you?" check (lib/placement.ts) climbs these stops.
//   stops   where someone can be placed: each year-one camp, then years two and three in four stretches each
//   qs      three knowledge questions per stop (fork: the lesson's story question; word: a match pair, "{term}" and
//           three meanings). `a` is the right option's index; the screen shuffles the order.

export const BANK_STATUS = "draft-unreviewed" as const;

export type BankQ = { day: number; kind: "fork"; q: string; o: string[]; a: number } | { day: number; kind: "word"; term: string; o: string[]; a: number };
export type BankStop = { first: number; last: number; camp: string; name: string; qs: BankQ[] };

export const PLACEMENT_BANK: Record<string, { lastWritten: number; stops: BankStop[] }> = {
  HINDUISM: { lastWritten: 1061, stops: [
    { first: 1, last: 21, camp: "Camp 1", name: "First steps", qs: [
      {"day":2,"kind":"fork","q":"the Mandukya Upanishad gives a to waking, u to dreaming and m to deep sleep. what does it give the fourth part?","o":["a fourth, louder sound.","the silence after the sound.","a second om."],"a":1},
      {"day":11,"kind":"word","term":"tat tvam asi","o":["that's what you are","the whole, under everything","a creator god in the stories"],"a":0},
      {"day":16,"kind":"fork","q":"you're Mirabai. you've married into a royal family that wants you to stop singing to Krishna in public. what do you do?","o":["stop singing and keep the peace.","sing only in private, where no one hears.","keep singing, with ordinary devotees."],"a":2},
    ] },
    { first: 22, last: 96, camp: "Camp 2", name: "The stories", qs: [
      {"day":36,"kind":"fork","q":"you're Dasharatha. a shining figure hands you a golden bowl of sweet rice for your queens. what do you do with it?","o":["give it all to your first queen.","divide it among all three queens.","eat it yourself for strength."],"a":1},
      {"day":59,"kind":"word","term":"Valmiki's Angada","o":["breaks through the roof and flies back","Vali's son, sent as the last messenger","couldn't lift the foot"],"a":0},
      {"day":81,"kind":"fork","q":"it's the new-moon night, the darkest of the month, and Lakshmi is said to visit homes. what do many families do?","o":["shut every door and window.","light the lamps and leave the way open.","wait until morning to celebrate."],"a":1},
    ] },
    { first: 97, last: 156, camp: "Camp 3", name: "The practices", qs: [
      {"day":106,"kind":"fork","q":"you're about to open a new shop. the first customer is at the door. what do many Hindu shopkeepers do first?","o":["open the door right away.","honor Ganesha by the till, with a garland.","wait until the end of the first day."],"a":1},
      {"day":127,"kind":"word","term":"Karva Chauth","o":["a fast from sunrise to moonrise","a vow, kept for a purpose","fasting; explained as staying near"],"a":0},
      {"day":145,"kind":"fork","q":"it's eleven forty-five on Janmashtami. you've fasted all day and you're starving. what do people do?","o":["eat now, since it's close enough.","wait, sing, and break the fast after midnight.","go to bed and eat in the morning."],"a":1},
    ] },
    { first: 157, last: 231, camp: "Camp 4", name: "The text", qs: [
      {"day":172,"kind":"fork","q":"you're Arjuna. you've heard that action binds. what does Krishna say the wise person does?","o":["stops acting completely.","acts fully, without clinging to the fruit.","acts only when the outcome is certain."],"a":1},
      {"day":194,"kind":"word","term":"Narada, Asita, Devala, Vyasa","o":["sages who called Krishna supreme","a divine glory, a power","in which things should I think of you?"],"a":0},
      {"day":215,"kind":"fork","q":"you're choosing what to do, and desire is pulling hard one way. what does Gita 16.24 say to steer by?","o":["whatever you want most right now.","let scripture be your measure.","whatever most people are doing."],"a":1},
    ] },
    { first: 232, last: 331, camp: "Camp 5", name: "The depths", qs: [
      {"day":252,"kind":"fork","q":"you've learned everything Death can teach. what does the Katha say happens when the knots of the heart are cut?","o":["you must leave this life.","the mortal becomes immortal, even here.","nothing changes."],"a":1},
      {"day":282,"kind":"word","term":"adhyasa","o":["superimposition","real","the rope, misseen"],"a":0},
      {"day":310,"kind":"fork","q":"you're Shvetaketu. you've broken open a banyan seed and see nothing inside. what does your father say?","o":["then there's nothing there: trust your eyes.","from that finest essence, the great tree stands. believe it.","try a different seed."],"a":1},
    ] },
    { first: 332, last: 420, camp: "Year 2", name: "The principal Upanishads", qs: [
      {"day":350,"kind":"fork","q":"you're the man from Gandhara. someone unties your blindfold and points: home is that way. what do you do?","o":["wait for them to take you there.","walk, asking your way from village to village.","stay put: it's too far."],"a":1},
      {"day":375,"kind":"word","term":"Ushasta","o":["show me the self, like a cow","the one who breathes in and out","you cannot see the seer of seeing"],"a":0},
      {"day":403,"kind":"fork","q":"the Aitareya counts three births. the first is in the father, the second from the mother. what is the third?","o":["the day you become a parent.","the day you depart this life and are born again.","the day of initiation into study."],"a":1},
    ] },
    { first: 421, last: 513, camp: "Year 2", name: "The Yoga Sutras of Patanjali", qs: [
      {"day":434,"kind":"fork","q":"you're absorbed so deeply in the breath that nothing else exists. which samadhi is this, in Patanjali's terms?","o":["samadhi with seed: the breath is still a support.","samadhi without seed: nothing is held.","not samadhi at all."],"a":0},
      {"day":467,"kind":"word","term":"parinama","o":["transformation, change of form","one, ten or a hundred by place","stays through lump, pot and shards"],"a":0},
      {"day":496,"kind":"fork","q":"you're the king of Anga. a holy boy in the forest can end your drought, but his father would never let him go. what do you do?","o":["send soldiers to take him.","send people to befriend him and invite him.","wait for the rain on your own."],"a":1},
    ] },
    { first: 514, last: 603, camp: "Year 2", name: "The Ramayana as a serial", qs: [
      {"day":533,"kind":"fork","q":"you're Rama, by the Tamasa at night. the whole city has followed you and will lose their homes if they keep going. what do you do?","o":["wake them and order them home.","let them come into the forest.","leave quietly before dawn and hide the tracks."],"a":2},
      {"day":559,"kind":"word","term":"Panchavati","o":["the place of five banyans","the vulture king, Dasharatha's friend","the river beside the hut"],"a":0},
      {"day":584,"kind":"fork","q":"you're Lakshmana. Rama holds out Sita's jewelry and asks if you know it. what do you say?","o":["yes, every piece.","only the anklets: I bowed at her feet each day.","I never looked at her jewelry at all."],"a":1},
    ] },
    { first: 604, last: 696, camp: "Year 2", name: "The Ramayana as a serial", qs: [
      {"day":623,"kind":"fork","q":"you're Sita. a mountain-sized Hanuman offers to fly you home tonight. what do you say?","o":["yes, at once.","no: Rama must come and win me back himself.","only if Lakshmana comes too."],"a":1},
      {"day":649,"kind":"word","term":"Kailasa","o":["the home of Shiva","made themselves invisible","torn loose and lifted"],"a":0},
      {"day":678,"kind":"fork","q":"you're Ganesha. the moon laughed at your fall and you cursed it. now the gods are pleading for the moon. what do you do?","o":["keep the curse as it is.","take it back completely.","soften it to one night a year."],"a":2},
    ] },
    { first: 697, last: 787, camp: "Year 3", name: "The Mahabharata as a serial", qs: [
      {"day":715,"kind":"fork","q":"you're Shantanu. your son gave up the throne and any children of his own so you could marry. what do you do?","o":["call off the marriage.","accept, and give him a boon.","accept, and say nothing."],"a":1},
      {"day":742,"kind":"word","term":"Draupadi","o":["speaks before he shoots","strings the bow","Karna's father, unknown to the arena"],"a":0},
      {"day":768,"kind":"fork","q":"you're Vidura. the game is going badly, and the blind king is listening. what do you do?","o":["keep quiet; it isn't your game.","speak to the king and beg him to stop it.","walk out of the hall."],"a":1},
    ] },
    { first: 788, last: 878, camp: "Year 3", name: "The Mahabharata as a serial", qs: [
      {"day":806,"kind":"fork","q":"you're Yudhishthira. one brother may live. a war may be coming. who do you choose?","o":["Arjuna, the archer you'll need.","Bhima, whose strength protects you all.","Nakula, Madri's son."],"a":2},
      {"day":833,"kind":"word","term":"Arjuna","o":["vowed to kill Jayadratha","said take the bow first","cut the bow from behind"],"a":0},
      {"day":860,"kind":"fork","q":"you're Kunti, standing in the river with your sons. they're offering water for everyone they lost, but not for Karna. what do you do?","o":["offer the water for him quietly, alone, later.","tell them, here, that Karna was their eldest brother.","say nothing, and keep the secret forever."],"a":1},
    ] },
    { first: 879, last: 962, camp: "Year 3", name: "Bhagavata Purana", qs: [
      {"day":896,"kind":"fork","q":"you're Krishna. Indra's storm is drowning the village, and everyone has turned to you. what do you do?","o":["send a storm back at Indra.","lift the hill and call everyone under it.","lead the village away to another valley."],"a":1},
      {"day":921,"kind":"word","term":"Niru and Nima","o":["the weaver couple who raised him","cried Ram, Ram on the steps","two lines that rhyme"],"a":0},
      {"day":945,"kind":"fork","q":"your day is loud and full. Vivekananda's ideal person has the same day. what do they do?","o":["leave and find a quiet place.","find the silence of the desert inside the activity.","work faster to finish the noise sooner."],"a":1},
    ] },
    { first: 963, last: 1061, camp: "Year 3", name: "Lineage track, year three", qs: [
      {"day":979,"kind":"fork","q":"you're Radha. you waited all night. at dawn he turns up, red-eyed, with marks of somewhere else. what do you do?","o":["let him in and say nothing.","tell him to go, and say exactly why.","leave the forest before he sees you."],"a":1},
      {"day":1012,"kind":"word","term":"abhyasa","o":["steady, repeated practice","letting go, loosening the grip","a practice kept as a discipline"],"a":0},
      {"day":1047,"kind":"fork","q":"you are Yudhishthira. Indra's chariot is waiting to take you to heaven, but he says the dog cannot come. what do you do?","o":["leave the dog and climb into the chariot.","refuse heaven rather than abandon the dog.","ask Indra for a day to think it over."],"a":1},
    ] },
  ] },
  ISLAM: { lastWritten: 1061, stops: [
    { first: 1, last: 21, camp: "Camp 1", name: "First steps", qs: [
      {"day":5,"kind":"fork","q":"it's Ramadan, and you're sick. what does the Qur'an say about the fast?","o":["fast anyway. no exceptions.","the sick may make up those days later.","the whole month no longer counts."],"a":1},
      {"day":11,"kind":"word","term":"mustaqim","o":["straight, standing upright","show us, guide us","guidance, and hadiya, a gift"],"a":0},
      {"day":16,"kind":"fork","q":"you run a shop. it's Friday, and the call to prayer comes in the middle of a sale. what does the Qur'an ask?","o":["close the shop for the whole day.","leave the trading, pray, then go back to work.","finish the sale first, then pray if there's time."],"a":1},
    ] },
    { first: 22, last: 96, camp: "Camp 2", name: "The stories", qs: [
      {"day":36,"kind":"fork","q":"the king says: I give life and cause death, and brings out two prisoners to prove it. you're Ibrahim. what do you do?","o":["explain why that isn't what you meant.","point to the sun: bring it up from the west.","walk out without a word."],"a":1},
      {"day":59,"kind":"word","term":"bakhs","o":["a short-changed price","good news! here's a boy!","sold him for a few coins"],"a":0},
      {"day":81,"kind":"fork","q":"you're 'Abd al-Muttalib. your little orphaned grandson has climbed onto the rug by the Ka'ba that none of your grown sons dare to sit on. his uncles move to pull him off. what do you say?","o":["leave him be.","teach him some respect.","find him his own rug."],"a":0},
    ] },
    { first: 97, last: 156, camp: "Camp 3", name: "The practices", qs: [
      {"day":107,"kind":"fork","q":"you're sitting in prayer with the companions, saying: peace be on Allah, peace on Jibril, peace on Mika'il. the Prophet ﷺ turns to you. what does he say?","o":["keep going, and add more names","don't say peace on Allah, for Allah is the Peace","stay silent in the sitting"],"a":1},
      {"day":127,"kind":"word","term":"eid mubarak","o":["a blessed Eid","from a root for returning","an odd number of dates"],"a":0},
      {"day":144,"kind":"fork","q":"a traveler, dusty and disheveled, raises his hands and cries 'O Lord, O Lord'. but everything he eats, drinks and wears is unlawful. what does the Prophet ﷺ ask?","o":["how could he not be answered?","how could he be answered?","why doesn't he pray in Arabic?"],"a":1},
    ] },
    { first: 157, last: 231, camp: "Camp 4", name: "The text", qs: [
      {"day":172,"kind":"fork","q":"two companions of the Prophet meet on the road and talk. before they part, what is it reported they did?","o":["shook hands and left","one recited Surah al-'Asr to the other","exchanged news of the market"],"a":1},
      {"day":195,"kind":"word","term":"hijr","o":["sense, what holds you back","dawn: light breaking through","Ibn Kathir: early Dhul Hijjah"],"a":0},
      {"day":216,"kind":"fork","q":"An-Nazi'at swears by 'those who pull out' and 'those who draw out gently'. who do most commentators say they are?","o":["the angels who take souls","farmers pulling up crops","the prophets"],"a":0},
    ] },
    { first: 232, last: 331, camp: "Camp 5", name: "The depths", qs: [
      {"day":251,"kind":"fork","q":"in the hadith, God loves a servant. who does he tell first?","o":["the servant, directly.","the angel Jibril.","no one. it stays hidden."],"a":1},
      {"day":282,"kind":"word","term":"Ka'b ibn Malik","o":["I had no excuse","came back with excuses","no one spoke to the three"],"a":0},
      {"day":312,"kind":"fork","q":"you're watching rain fall on dry ground. what does the Qur'an ask you to do with it?","o":["measure it.","ignore it, since it isn't scripture.","read it like a verse: ask what it points to."],"a":2},
    ] },
    { first: 332, last: 420, camp: "Year 2", name: "Al-Baqarah, the Cow", qs: [
      {"day":351,"kind":"fork","q":"you're traveling with the Prophet in Ramadan. some companions are fasting, some aren't. what happens between the two groups?","o":["the fasting ones scold the others.","they argue until the Prophet decides.","neither group finds fault with the other."],"a":2},
      {"day":376,"kind":"word","term":"arham","o":["wombs, and ties of kinship","a single soul","mercy, from the same root as womb"],"a":0},
      {"day":401,"kind":"fork","q":"the Hour is arriving, and you're holding a palm shoot. what does the report in Ahmad's Musnad say to do?","o":["drop it and pray.","plant it.","give it away."],"a":1},
    ] },
    { first: 421, last: 515, camp: "Year 2", name: "The Hijri year", qs: [
      {"day":440,"kind":"fork","q":"your sons come home with a bloody shirt and a story about a wolf. you suspect it isn't true. what does Ya'qub say?","o":["beautiful patience.","go back and find him.","I'll never speak to you again."],"a":0},
      {"day":468,"kind":"word","term":"Yusha'","o":["Musa's young companion","where you lose it, you'll find him","where the two seas meet"],"a":0},
      {"day":496,"kind":"fork","q":"you're Abu Bakr. you've sworn never to support Mistah again. then you hear: don't you want God to forgive you? what do you do?","o":["keep the oath; it was sworn before God.","say yes, by God, and go back to supporting him.","support him, but quietly tell people what he did."],"a":1},
    ] },
    { first: 516, last: 607, camp: "Year 2", name: "Al-Hujurat, the Private Rooms", qs: [
      {"day":533,"kind":"fork","q":"the companions hear that safety is for those who don't mix faith with wrong. they panic: who hasn't wronged himself? what does the Prophet say?","o":["nobody is safe, then.","it means shirk, as Luqman told his son.","only prophets are without wrong."],"a":1},
      {"day":562,"kind":"word","term":"Pharaoh","o":["let me kill Musa","would you kill a man for this?","I entrust my affair to Allah"],"a":0},
      {"day":588,"kind":"fork","q":"you ask why Allah made humanity in nations and tribes. what reason does 49:13 give?","o":["so each could rule over others.","so that you may know one another.","so that you stay apart."],"a":1},
    ] },
    { first: 608, last: 696, camp: "Year 2", name: "The book's great themes", qs: [
      {"day":626,"kind":"fork","q":"the call for the Friday prayer is heard. you're a little late. what does the hadith say to do?","o":["run as fast as you can.","walk with calm and dignity.","skip it and pray at home."],"a":1},
      {"day":652,"kind":"word","term":"Khadijah","o":["heard: wrap me, wrap me","the one wrapped up","standing the night in prayer"],"a":0},
      {"day":679,"kind":"fork","q":"a Christian or Jewish neighbor disagrees with you about faith. what manner does surah twenty-nine set?","o":["avoid the subject entirely.","argue only in the best way.","argue until one side wins."],"a":1},
    ] },
    { first: 697, last: 797, camp: "Year 3", name: "Medina", qs: [
      {"day":717,"kind":"fork","q":"Nafisa asks him why he hasn't married. he has almost nothing to offer. what does he say?","o":["that he has no wish to marry.","that he has nothing to marry with.","that his uncles must choose for him."],"a":1},
      {"day":747,"kind":"word","term":"Hisham ibn Amr","o":["sent a camel of food into the valley","spoke out at the Ka'ba","went to take the document down"],"a":0},
      {"day":777,"kind":"fork","q":"you're Abd al-Rahman ibn Awf, standing in the row at Badr. a young man beside you whispers: uncle, do you know Abu Jahl? what do you do?","o":["tell him to go back to the camp.","ask what he wants with him, then point him out.","pretend you didn't hear."],"a":1},
    ] },
    { first: 798, last: 880, camp: "Year 3", name: "Later companions and their stories", qs: [
      {"day":814,"kind":"fork","q":"you are a companion holding captives from her tribe. you hear the Prophet has just married Juwayriyyah. what do you do?","o":["keep them; nothing has been commanded.","free them, since they're now his in-laws.","ask the Prophet what he wants done."],"a":1},
      {"day":839,"kind":"word","term":"Salim","o":["said he slept little after that","named the places where he prayed","told the Prophet about his dream"],"a":0},
      {"day":864,"kind":"fork","q":"you're at the saqifah. Abu Bakr has put forward Umar and Abu Ubaydah and said: pledge to either. what does Umar do?","o":["accepts and asks for pledges to himself.","says stretch out your hand, and pledges to Abu Bakr.","walks out to fetch the family."],"a":1},
    ] },
    { first: 881, last: 964, camp: "Year 3", name: "The Abbasids and the House of Wisdom", qs: [
      {"day":898,"kind":"fork","q":"you're putting the four in the Sunni order. who comes fourth?","o":["Abu Bakr","Uthman","Ali"],"a":2},
      {"day":922,"kind":"word","term":"qanun","o":["a rule, a standard","explained the book that defeated him","he went to the mosque and prayed"],"a":0},
      {"day":947,"kind":"fork","q":"you're a student who has traveled far to Cairo. there are many teachers in the mosque, each by a different pillar. what do you do?","o":["wait for a classroom with desks to open.","join a ring on the floor by a pillar.","study alone from books you brought."],"a":1},
    ] },
    { first: 965, last: 1061, camp: "Year 3", name: "Persia, the Turks and the great empires", qs: [
      {"day":983,"kind":"fork","q":"you look after Hagia Sophia as a mosque. gold mosaics of Mary and Christ are on the walls, and prayer is about to begin. what do you do?","o":["remove the mosaics for good.","veil the images while prayer is held.","leave everything exactly as it is."],"a":1},
      {"day":1013,"kind":"word","term":"Qur'an 3:92","o":["spend of that which ye love","at Khaybar: kept, its harvest given","property set aside forever for good"],"a":0},
      {"day":1041,"kind":"fork","q":"you're in Cairo, and the ruler is arriving by night at the start of the fasting month. the streets are dark. what do you do, in the story people tell?","o":["stay indoors until morning.","go out carrying lanterns to light his way.","light fires on the rooftops."],"a":1},
    ] },
  ] },
  JUDAISM: { lastWritten: 1061, stops: [
    { first: 1, last: 21, camp: "Camp 1", name: "First steps", qs: [
      {"day":4,"kind":"fork","q":"you're poor. it's Shabbat and Hanukkah at once, and you can afford only one light. which does the Talmud say to buy?","o":["the Hanukkah light, because it's rarer.","the Shabbat light, for peace in the home.","neither. save the money."],"a":1},
      {"day":10,"kind":"word","term":"tzedek","o":["justice, righteousness","help so they won't need help","so nobody is ashamed"],"a":0},
      {"day":17,"kind":"fork","q":"a year later you're in the same situation, same temptation, same strength. by Maimonides' test, what makes it complete teshuvah?","o":["you avoid the situation entirely.","you don't do it, though you could.","you feel very sorry afterward."],"a":1},
    ] },
    { first: 22, last: 96, camp: "Camp 2", name: "The stories", qs: [
      {"day":37,"kind":"fork","q":"you're Abram, seventy-five and settled. God says go, to a land I will show you, and gives no name. what do you do?","o":["ask for the name of the land first.","stay until you're sure.","pack up and go."],"a":2},
      {"day":59,"kind":"word","term":"Jeremiah","o":["Rachel weeping for her children","I have wrestled with my sister","may He add"],"a":0},
      {"day":80,"kind":"fork","q":"you're Moses, a prince of Egypt. you've gone out to see your people, and you see an Egyptian beating a Hebrew. what does the text say you do first?","o":["call the guards.","look this way and that way.","go back to the palace."],"a":1},
    ] },
    { first: 97, last: 156, camp: "Camp 3", name: "The practices", qs: [
      {"day":109,"kind":"fork","q":"you've just woken up. you haven't washed, you're half asleep, and the phone is buzzing. when does Modeh Ani get said?","o":["after coffee.","right now, still in bed.","at the synagogue later."],"a":1},
      {"day":127,"kind":"word","term":"ushpizin","o":["biblical guests welcomed each night","a booth, a temporary hut","cut branches, stars show through"],"a":0},
      {"day":144,"kind":"fork","q":"you're hosting a Jewish friend for dinner and you're not sure if they keep kosher. what's the best first step?","o":["assume they don't and cook anything.","ask them what they keep.","just serve salad and hope."],"a":1},
    ] },
    { first: 157, last: 231, camp: "Camp 4", name: "The text", qs: [
      {"day":172,"kind":"fork","q":"you're Abram. God has promised you a great nation, blessing and a great name. what's the last thing God says in that verse?","o":["keep it for yourself.","be thou a blessing.","tell no one."],"a":1},
      {"day":194,"kind":"word","term":"Rashi","o":["like pulling a cork from a bottle","waited for everyone to gather","tended her father's flock"],"a":0},
      {"day":215,"kind":"fork","q":"you're Jacob, newly arrived in Egypt. the king asks how old you are. what do you say?","o":["just the number, with a smile.","the number, and the truth that the years were hard.","that your life has been richly blessed."],"a":1},
    ] },
    { first: 232, last: 331, camp: "Camp 5", name: "The depths", qs: [
      {"day":252,"kind":"fork","q":"you do a good thing every week, but only because you have to. what does Rabban Gamaliel's saying hope for?","o":["that you stop, since your heart isn't in it.","that over time you come to want it.","that you keep doing it and never mind why."],"a":1},
      {"day":281,"kind":"word","term":"Elijah","o":["reported that God smiled","outvoted, then put under a ban","dressed in black to tell him gently"],"a":0},
      {"day":311,"kind":"fork","q":"your teacher, the Maggid, has died. there's no single successor. what do his students do?","o":["choose one of them to lead everyone.","go home and each become a teacher in his own place.","close the circle and stop teaching."],"a":1},
    ] },
    { first: 332, last: 424, camp: "Year 2", name: "Exodus finished", qs: [
      {"day":350,"kind":"fork","q":"you see the donkey of someone who hates you, lying under its load. no one else is around. what does the Torah say?","o":["walk past; it's his problem.","help him release it, side by side.","tell someone else to help."],"a":1},
      {"day":378,"kind":"word","term":"chazak","o":["be strong","and let us be strengthened","the book of exile and redemption"],"a":0},
      {"day":405,"kind":"fork","q":"you're writing the instructions for the Day of Atonement. where do you begin?","o":["with the date on the calendar.","with the death of Aaron's sons.","with the high priest's clothes."],"a":1},
    ] },
    { first: 425, last: 516, camp: "Year 2", name: "Numbers, the wilderness", qs: [
      {"day":445,"kind":"fork","q":"your sister has just spoken against you, and now she's stricken. your brother begs you to pray. what does Moses do?","o":["remind God that she spoke against him first.","cry out five words: heal her now, O God, I beseech Thee.","wait seven days, then pray."],"a":1},
      {"day":471,"kind":"word","term":"neder","o":["a vow, a binding promise","he shall not break his word","without a vow"],"a":0},
      {"day":498,"kind":"fork","q":"you want to give at the highest of Maimonides' eight levels. what do you do?","o":["give a large gift with your name on it.","help someone with a loan, a partnership or a job.","give whenever you feel moved."],"a":1},
    ] },
    { first: 517, last: 607, camp: "Year 2", name: "The siddur, walked in order", qs: [
      {"day":535,"kind":"fork","q":"Moses has died, and a grave could easily become a shrine. what does the Torah's account do?","o":["describe the grave so it can be marked.","say no one knows where he lies.","carry his body into the land."],"a":1},
      {"day":562,"kind":"word","term":"hamechadesh","o":["who renews","who forms light","I form the light, and create darkness"],"a":0},
      {"day":590,"kind":"fork","q":"you're Obadiah, a convert. the Amidah says God of our fathers, God of Abraham. what does Maimonides tell you?","o":["change it to God of your fathers.","say it as written: Abraham is your father too.","skip that line."],"a":1},
    ] },
    { first: 608, last: 696, camp: "Year 2", name: "The Jewish year in depth", qs: [
      {"day":623,"kind":"fork","q":"Ben Zoma asks: who is rich? which answer does he give?","o":["the one with the most land.","the one who is happy with their portion.","the one who gives the most away."],"a":1},
      {"day":652,"kind":"word","term":"Maimonides","o":["don't be cruel; forgive","Yom Kippur can't fix it alone","how often to try before the burden lifts"],"a":0},
      {"day":679,"kind":"fork","q":"a child at the seder sits silent. they haven't asked anything all night. what does the Haggadah say to do?","o":["wait until they ask.","open the conversation for them.","give them the laws in full."],"a":1},
    ] },
    { first: 697, last: 781, camp: "Year 3", name: "The Former Prophets", qs: [
      {"day":714,"kind":"fork","q":"you're Jael. the enemy captain, fleeing the battle, is at your tent. your household is at peace with his king. what does the text say you do?","o":["turn him away.","go out and invite him in.","run to find Barak."],"a":1},
      {"day":738,"kind":"word","term":"Michal","o":["Saul's daughter, David's wife","laid in the bed in David's place","the pillow where his head would be"],"a":0},
      {"day":763,"kind":"fork","q":"you're a king known for wisdom. the Torah warns kings against many wives, lest the heart turn. what do you tell yourself?","o":["the warning is for kings less wise than me.","keep the limit, because even wisdom can drift.","ask a prophet to decide for you."],"a":0},
    ] },
    { first: 782, last: 886, camp: "Year 3", name: "The Writings", qs: [
      {"day":804,"kind":"fork","q":"you've been carried off to the city that conquered your home. a letter arrives from Jeremiah. what does it say?","o":["resist the city at every turn.","build, plant, and seek the city's peace.","wait at the gate; you'll be home soon."],"a":1},
      {"day":834,"kind":"word","term":"Elimelech","o":["dies in Moab","weeps and goes back","bitter"],"a":0},
      {"day":865,"kind":"fork","q":"you're Esther, newly taken to the palace. Mordecai has told you not to say who your people are. what do you do?","o":["tell everyone. you have nothing to hide.","run away from the palace.","keep it to yourself, as Mordecai asked."],"a":2},
    ] },
    { first: 887, last: 970, camp: "Year 3", name: "The story after the Bible", qs: [
      {"day":903,"kind":"fork","q":"you're a sage in the study hall. Rabbi Akiva, an honored teacher, says this commander is the promised king. what do you say?","o":["agree, since Akiva said it.","tell him plainly that he's wrong.","stay quiet and wait."],"a":1},
      {"day":929,"kind":"word","term":"David","o":["a merchant who supported the family","where his ship went down","the judge who received the letter"],"a":0},
      {"day":953,"kind":"fork","q":"you are a rabbi in Kraków. a new code from Tzfat doesn't match your community's customs. what do you do?","o":["reject the book entirely.","write your own code from scratch.","add notes where your custom differs."],"a":2},
    ] },
    { first: 971, last: 1061, camp: "Year 3", name: "The story after the Bible", qs: [
      {"day":989,"kind":"fork","q":"you are the company's directors in Amsterdam. your governor wants the Jewish refugees sent away. Jewish merchants ask you to let them stay. what do you decide?","o":["send them away.","let them stay, if their community cares for its own poor.","let them stay, with no conditions at all."],"a":1},
      {"day":1016,"kind":"word","term":"Mordecai Anielewicz","o":["a young commander of the fighters","dug under the ghetto's buildings","blown up to mark the end"],"a":0},
      {"day":1044,"kind":"fork","q":"you're Rebecca Gratz. Jewish children in your city have no Jewish school, and their Christian friends go to Sunday school. what do you do?","o":["send them to the church schools.","start a Jewish school on the day they're free.","wait for the synagogue to do it."],"a":1},
    ] },
  ] },
  BUDDHISM: { lastWritten: 1061, stops: [
    { first: 1, last: 21, camp: "Camp 1", name: "First steps", qs: [
      {"day":5,"kind":"fork","q":"the Buddha has just woken up. he could teach anyone. who does he walk to find first, in the story?","o":["the king of the region.","five old companions.","his family at the palace."],"a":1},
      {"day":11,"kind":"word","term":"anicca","o":["not lasting · impermanence","permanent, lasting","the bud in April"],"a":0},
      {"day":16,"kind":"fork","q":"the Buddha finds a monk lying sick and alone, and nobody is looking after him. what does he do?","o":["sends someone to find a doctor.","washes and cares for him himself.","asks the monk what he did to deserve it."],"a":1},
    ] },
    { first: 22, last: 96, camp: "Camp 2", name: "The stories", qs: [
      {"day":40,"kind":"fork","q":"you're the prince, now robed. Channa begs to stay with you. what do you do?","o":["let Channa and Kanthaka come along.","send them both home with your jewels.","keep the horse, send Channa home."],"a":1},
      {"day":59,"kind":"word","term":"Brahma Sahampati","o":["knelt and asked him to teach","people who could understand","people at every depth"],"a":0},
      {"day":73,"kind":"fork","q":"you're Angulimala. you've been told to say, 'since I was born, I have never intended to take a life.' what do you do?","o":["say it anyway, to help her.","tell the Buddha it would be a lie.","refuse and walk away."],"a":1},
    ] },
    { first: 97, last: 156, camp: "Camp 3", name: "The practices", qs: [
      {"day":105,"kind":"fork","q":"you're a monk meditating in a forest, and the spirits there frighten you. what does the commentary say the Buddha gave you?","o":["a charm to drive them away.","the Metta Sutta, to recite with kindness.","permission to leave the forest."],"a":1},
      {"day":127,"kind":"word","term":"Rahula","o":["set out water for his father's feet","left a little water in the dipper","look before you speak or act"],"a":0},
      {"day":142,"kind":"fork","q":"you're Ananda. you've noticed every scent follows the wind. what do you ask the Buddha?","o":["how to make incense stronger.","whether any scent travels against the wind.","why temples use so much incense."],"a":1},
    ] },
    { first: 157, last: 231, camp: "Camp 4", name: "The text", qs: [
      {"day":171,"kind":"fork","q":"you're a pickpocket in a crowd listening to the Buddha. the teaching starts to reach you. what does the story say happened?","o":["you steal anyway; that's what you came for.","you listen, forget to steal, and see the truth.","you leave before it gets to you."],"a":1},
      {"day":193,"kind":"word","term":"kiccha","o":["hard, difficult, rare","how rare human birth is","the Buddha, led by no desire"],"a":0},
      {"day":220,"kind":"fork","q":"you're Uggasena, balanced at the top of a bamboo pole in front of a crowd. the Buddha speaks to you. what does he say?","o":["climb down carefully and come to the monastery.","let go of before, behind and between, and cross over.","hold on tight; don't fall."],"a":1},
    ] },
    { first: 232, last: 331, camp: "Camp 5", name: "The depths", qs: [
      {"day":246,"kind":"fork","q":"you're lost in a long text with many sections. what does the opening of the Satipatthana Sutta give you?","o":["a list of rules.","a map: four foundations every section fits into.","a story about the Buddha's childhood."],"a":1},
      {"day":282,"kind":"word","term":"Huineng","o":["your minds are moving","the flag is moving","the wind is moving"],"a":0},
      {"day":308,"kind":"fork","q":"you've just heard that human life is precious and death's timing unknown. a Tibetan teacher asks what you'll do with that. which answer fits the four thoughts?","o":["panic and try to do everything at once.","let it turn the mind toward what matters, steadily.","forget it; it's too gloomy."],"a":1},
    ] },
    { first: 332, last: 400, camp: "Year 2", name: "The eightfold path, factor by factor", qs: [
      {"day":341,"kind":"fork","q":"you're Paharada, lord of the titans, telling the Buddha about the ocean's wonders. he replies about his teaching. what does he say its one taste is?","o":["the taste of salt.","the taste of freedom.","the taste of sweetness."],"a":1},
      {"day":365,"kind":"word","term":"samphappalāpa","o":["idle chatter","right, whole, complete","speech, the voice"],"a":0},
      {"day":388,"kind":"fork","q":"you're the Buddha. Sona, his feet bleeding from too much walking practice, is thinking of quitting. what do you do?","o":["tell him to push through the pain.","ask him about tuning a lute.","send him home to his family."],"a":1},
    ] },
    { first: 401, last: 521, camp: "Year 2", name: "The Middle-Length Sayings, in order", qs: [
      {"day":426,"kind":"fork","q":"you went forth, and people now bring you gifts and praise your name. what does the Buddha's simile call that?","o":["the heartwood.","the twigs and leaves.","the sapwood."],"a":1},
      {"day":461,"kind":"word","term":"Moggallāna","o":["asked: only for forest monks?","the forest monk who came in","gave the talk on coming back"],"a":0},
      {"day":498,"kind":"fork","q":"you're Yama, the judge of the dead. at the end of the discourse, what do you wish for?","o":["more power over the dead.","to be born human, hear a Buddha and understand.","to never meet another wrongdoer."],"a":1},
    ] },
    { first: 522, last: 610, camp: "Year 2", name: "The Long Discourses", qs: [
      {"day":541,"kind":"fork","q":"you're the Buddha. two students ask which path leads to union with Brahma. what do you ask first?","o":["has anyone in your teachers' line seen Brahma?","which teacher has more students?","which path is older?"],"a":0},
      {"day":565,"kind":"word","term":"Atanatiya","o":["verses named for the city of Atanata","guardian king of the north","first of the seven Buddhas honored"],"a":0},
      {"day":591,"kind":"fork","q":"you're Tissa. you've asked Kassapa what he means by the rotten smell. what's his answer?","o":["eating any meat at all.","cruel, dishonest and proud deeds.","skipping a fast day."],"a":1},
    ] },
    { first: 611, last: 696, camp: "Year 2", name: "The Connected and the Numbered Sayings", qs: [
      {"day":627,"kind":"fork","q":"you want to make real progress on the path. the Itivuttaka's first teaching offers a deal. what is it?","o":["master eight things and you might succeed.","abandon just greed, and the Buddha guarantees non-return.","give away everything you own."],"a":1},
      {"day":655,"kind":"word","term":"Anguttara","o":["increasing by one factor","eleven","teachings about three things"],"a":0},
      {"day":676,"kind":"fork","q":"you're Ananda. rubbing your teacher's arms, you see how old his body has become. what do you do?","o":["say nothing; it would be disrespectful.","say it out loud: how changed you are.","go and find a doctor."],"a":1},
    ] },
    { first: 697, last: 780, camp: "Year 3", name: "The great disciples", qs: [
      {"day":713,"kind":"fork","q":"you're the prince. you've climbed Arada's ladder to the state of nothingness, and he calls it liberation. what question do you ask?","o":["how do I stay here forever?","if the knower is still here, can it be bound again?","is there a harder practice than this?"],"a":1},
      {"day":738,"kind":"word","term":"Mahakassapa","o":["asks the questions","answers from memory","spoken at the rest house in Ambalatthika"],"a":0},
      {"day":763,"kind":"fork","q":"you're Visakha. your father-in-law has called elders to judge you, and holds up your father's riddles as proof you're strange. what do you do?","o":["apologize, and promise to forget the riddles.","explain what each riddle means.","go home to your father's house."],"a":1},
    ] },
    { first: 781, last: 899, camp: "Year 3", name: "After the Buddha: India, Sri Lanka and Southeast Asia", qs: [
      {"day":805,"kind":"fork","q":"you're Ananda. word comes that Sariputta has died, and everything goes dark. what do you do?","o":["say nothing. a monk shouldn't grieve.","go to the Buddha and tell him how it is.","leave the order."],"a":1},
      {"day":840,"kind":"word","term":"Sama","o":["the son at the river","blinded by a snake's venom","the king who shot the arrow"],"a":0},
      {"day":876,"kind":"fork","q":"you've traveled a long way to Nalanda. at the gate a monk asks you a hard question about the teaching. what happens next?","o":["you show a letter from a king and walk in.","you answer, and only if you answer well do you get in.","you pay a fee to the gatekeeper."],"a":1},
    ] },
    { first: 900, last: 955, camp: "Year 3", name: "The northern roads: China, Korea, Japan, Tibet and the wider world", qs: [
      {"day":912,"kind":"fork","q":"you're Bodhidharma. an emperor who has built temples and fed monks asks how much merit he's made. what do you say?","o":["a great deal, more than anyone.","no merit.","enough for a good rebirth."],"a":1},
      {"day":928,"kind":"word","term":"Honen","o":["call Amida's name with trust","just sitting","chant the Lotus Sutra's title"],"a":0},
      {"day":943,"kind":"fork","q":"you're Wang Jie. you want to honor your two parents. what do you do?","o":["build them a large house.","have the Diamond Sutra printed, to be given away freely.","keep a sutra locked away for your family alone."],"a":1},
    ] },
    { first: 956, last: 1061, camp: "Year 3", name: "The great teachers", qs: [
      {"day":976,"kind":"fork","q":"you're Gampopa, a trained monk in Atisha's tradition. you meet Milarepa and his mountain meditation. what do you do with the two?","o":["drop the monastery and become a wandering yogi.","bring the two streams together.","stay in the monastery and forget the cave."],"a":1},
      {"day":1009,"kind":"word","term":"Chiyono","o":["a nun who woke up as it spilled","held the old bucket together","a reflection, held by water"],"a":0},
      {"day":1043,"kind":"fork","q":"you are the Buddha on your alms round. a brahmin at his fire shouts at you to stop, calling you an outcast. what do you do?","o":["walk on in silence","ask whether he knows what makes an outcast","tell him your family is noble"],"a":1},
    ] },
  ] },
  SIKHISM: { lastWritten: 1061, stops: [
    { first: 1, last: 21, camp: "Camp 1", name: "First steps", qs: [
      {"day":5,"kind":"fork","q":"you have one breath to describe God, right after the symbol for one. what comes next?","o":["a list of God's rules.","truth is the name; the creator.","a warning about punishment."],"a":1},
      {"day":11,"kind":"word","term":"japna","o":["to repeat, to recite","earn it clean","share it first"],"a":0},
      {"day":18,"kind":"fork","q":"you're Duni Chand. the Guru hands you a needle to give back in the next world. your wife asks how you'll carry it. what do you do?","o":["hide it somewhere clever.","go back to Nanak and ask what to do.","laugh it off and keep the flags flying."],"a":1},
    ] },
    { first: 22, last: 96, camp: "Camp 2", name: "The stories", qs: [
      {"day":37,"kind":"fork","q":"you're a tired traveler in Mecca. a judge wakes you, angry that your feet point at the house of God. what do you say?","o":["apologize and move away.","ask him to turn your feet where God is not.","argue that the building is only stone."],"a":1},
      {"day":59,"kind":"word","term":"Hargobind","o":["the child the stories say was spared","the eldest brother, a rival","Bhai Gurdas's name for his followers"],"a":0},
      {"day":79,"kind":"fork","q":"you're the Guru. you're told: convert, or show a miracle, or die. what do you do?","o":["show a miracle and go free.","refuse all three.","convert in name and keep your faith in secret."],"a":1},
    ] },
    { first: 97, last: 156, camp: "Camp 3", name: "The practices", qs: [
      {"day":110,"kind":"fork","q":"you're at the end of an evening program. the harmonium starts a slow tune and the room begins to sing. you don't read Gurmukhi. what can you do?","o":["stay silent; it's for people who know the words.","join in: there's only one word, Waheguru.","look for a translation on your phone."],"a":1},
      {"day":127,"kind":"word","term":"mala","o":["bead by bead","the Name on the breath","true name"],"a":0},
      {"day":145,"kind":"fork","q":"Guru Nanak pictures a life as a farm: the mind is the plowman, the body is the field. what does he make the seed?","o":["hard work.","the Name.","money saved for next year."],"a":1},
    ] },
    { first: 157, last: 231, camp: "Camp 4", name: "The text", qs: [
      {"day":171,"kind":"fork","q":"pauri five opens with two things the One cannot be. which pair?","o":["seen and heard.","installed and made.","praised and thanked."],"a":1},
      {"day":194,"kind":"word","term":"aape beej","o":["you yourself sow","washed by water","washed with soap"],"a":0},
      {"day":216,"kind":"fork","q":"you've been given one tongue. in the opening of Pauri 32, what does Nanak wish for?","o":["a quieter tongue.","a hundred thousand tongues, then two million.","a tongue that speaks every language."],"a":1},
    ] },
    { first: 232, last: 331, camp: "Camp 5", name: "The depths", qs: [
      {"day":249,"kind":"fork","q":"one person can explain truth perfectly but cheats at work. another never talks about it and deals straight. what does Guru Nanak's line put highest?","o":["the one who explains truth best.","truthful living, the straight dealing.","neither: truth can't be reached."],"a":1},
      {"day":282,"kind":"word","term":"banda","o":["servant, one bound to another","his birth name","his name as a hermit"],"a":0},
      {"day":311,"kind":"fork","q":"you're Jaswant Singh Khalra in Amritsar in the 1990s. cremation records show thousands of bodies burned as unidentified. what do you do?","o":["keep quiet; it's too dangerous.","make the records public and ask for justice.","leave Punjab for good."],"a":1},
    ] },
    { first: 332, last: 420, camp: "Year 2", name: "Jaap Sahib", qs: [
      {"day":349,"kind":"fork","q":"the old myth says a bull holds the earth on its back. what does Guru Nanak say the bull really is?","o":["an animal sent from heaven.","dharma, the child of compassion.","a story with no meaning."],"a":1},
      {"day":376,"kind":"word","term":"ghat ghat","o":["every heart, every body","the inner knower","the good and the bad"],"a":0},
      {"day":403,"kind":"fork","q":"the day is ending and a family gathers for the evening prayer. where do the six pauris of the Anand come?","o":["in Kirtan Sohila, at bedtime.","inside Rehras, the evening prayer.","they're never said in the evening."],"a":1},
    ] },
    { first: 421, last: 509, camp: "Year 2", name: "Sukhmani Sahib", qs: [
      {"day":439,"kind":"fork","q":"you want peace, the jewel the bani is named for. what does the first stanza of Sukhmani say to do?","o":["think hard about God, once, deeply.","remember, remembering again and again.","wait until your troubles end."],"a":1},
      {"day":465,"kind":"word","term":"dusman","o":["an enemy","in the company of the holy","a friend"],"a":0},
      {"day":493,"kind":"fork","q":"you're Guru Nanak. a rich official invites you to a feast; a poor carpenter offers plain bread. where do you go?","o":["the official's feast.","the carpenter's house.","neither; you fast."],"a":1},
    ] },
    { first: 510, last: 610, camp: "Year 2", name: "Guru Tegh Bahadur's bani", qs: [
      {"day":532,"kind":"fork","q":"you've read all twenty-four ashtpadis. according to the rahao line, what is Sukhmani's jewel of peace?","o":["God's ambrosial Name.","a calm mood.","finishing the reading."],"a":0},
      {"day":560,"kind":"word","term":"pauri","o":["a step, a rung, a stanza","an old Punjabi ballad of heroes","wander and make you see"],"a":0},
      {"day":589,"kind":"fork","q":"the first salok wants the mind to love the Lord. what picture does it give?","o":["a guest who visits on holidays.","a fish in water.","a bird that flies far away."],"a":1},
    ] },
    { first: 611, last: 696, camp: "Year 2", name: "The Ardas, line by line", qs: [
      {"day":626,"kind":"fork","q":"a question comes up that affects Sikhs everywhere. where does tradition look for a hukamnama binding on the whole community?","o":["the nearest gurdwara.","the Akal Takht in Amritsar.","any large gathering."],"a":1},
      {"day":653,"kind":"word","term":"maataa","o":["mother","father","brother"],"a":0},
      {"day":682,"kind":"fork","q":"it's the Katak full moon. what are Sikhs celebrating?","o":["the founding of the Khalsa.","Guru Nanak's gurpurab, his birth.","the start of the solar year."],"a":1},
    ] },
    { first: 697, last: 779, camp: "Year 3", name: "The Bhagats of the Granth", qs: [
      {"day":713,"kind":"fork","q":"you're a scholar and a Persian poet, and you've come to the Guru. what do you do with your poetry?","o":["give it up: devotion has no room for art.","turn it toward the Guru and the One.","keep it for the royal courts only."],"a":1},
      {"day":738,"kind":"word","term":"Raja Shivnabh","o":["the king who waited","the Sikh trader on the island","fine speeches, hands out for gifts"],"a":0},
      {"day":763,"kind":"fork","q":"you've spotted a colleague's mistake, and you're good at spotting them. Farid has addressed his couplet to you. what does it ask?","o":["write it down so it isn't forgotten.","point it out to everyone, for fairness.","bow your head and look within your own collar."],"a":2},
    ] },
    { first: 780, last: 886, camp: "Year 3", name: "The Khalsa's hard century", qs: [
      {"day":802,"kind":"fork","q":"you're Nanak, on the road with your father's coins, and you meet holy men who haven't eaten. what do you do?","o":["buy goods and sell them for a profit, as asked.","feed them, and call that the true bargain.","split the money and do a little of both."],"a":1},
      {"day":833,"kind":"word","term":"Mian Mir","o":["the Sufi of Lahore, friend of Guru Arjan","played the rebab for Guru Nanak","carried the Guru in disguise"],"a":0},
      {"day":865,"kind":"fork","q":"you're a Sikh horseman. an army has caught your people's slow column of families in the open. your horse is fast. what do you do?","o":["scatter and ride hard, as you've always done.","form a ring around the families and keep them moving.","ride ahead to find help."],"a":1},
    ] },
    { first: 887, last: 956, camp: "Year 3", name: "Maharaja Ranjit Singh", qs: [
      {"day":902,"kind":"fork","q":"you're a builder's son leading a misl. the Harmandir needs protecting. what do you give?","o":["a chest of gold for the shrine.","towers to watch the roads from.","a new wall around the whole city."],"a":1},
      {"day":922,"kind":"word","term":"Hazur Sahib","o":["the gurdwara at Nanded","where the Tenth Guru was born","where his earthly life ended"],"a":0},
      {"day":942,"kind":"fork","q":"you're Duleep Singh. you've bought an English country estate and are rebuilding the hall. what do you do with the rooms inside?","o":["make them plain English rooms.","make some of them look like an Indian palace.","leave them as they were."],"a":1},
    ] },
    { first: 957, last: 1061, camp: "Year 3", name: "The twentieth century and today", qs: [
      {"day":978,"kind":"fork","q":"you're a young man in court in Lahore. the charge is serious. what does Kartar Singh do?","o":["deny everything to save his life.","speak openly about what he had done.","blame the older leaders."],"a":1},
      {"day":1009,"kind":"word","term":"Ang 8","o":["water the father, earth the mother","bigger harvests of wheat and rice","pulled water from deep underground"],"a":0},
      {"day":1035,"kind":"fork","q":"someone in the langar hall says women's voices count for less in the Guru's house. which answer comes from the Guru Granth Sahib?","o":["why call her lesser, from whom kings are born?","women may sing, but only at home.","it depends on the village."],"a":0},
    ] },
  ] },
  CATHOLIC: { lastWritten: 1061, stops: [
    { first: 1, last: 21, camp: "Camp 1", name: "First steps", qs: [
      {"day":5,"kind":"fork","q":"you're at the table the night before Jesus dies. he breaks the bread and hands it around. what does he ask you to do?","o":["keep it as a relic.","do this in memory of him.","never speak of it again."],"a":1},
      {"day":11,"kind":"word","term":"Gabriel","o":["hail, full of grace","blessed is the fruit of thy womb","pray for us sinners"],"a":0},
      {"day":17,"kind":"fork","q":"Jesus says his flesh is real food, and many followers find it too hard and start leaving. what does he do?","o":["calls them back and explains it's only a metaphor.","lets them go.","changes the subject."],"a":1},
    ] },
    { first: 22, last: 96, camp: "Camp 2", name: "The stories", qs: [
      {"day":37,"kind":"fork","q":"you're Matthew. a teacher has just called you from your booth, and you've followed him. what do you do next?","o":["keep it quiet so your old life doesn't embarrass him.","throw a dinner and invite all your friends, the wrong crowd included.","go to the synagogue to make amends first."],"a":1},
      {"day":59,"kind":"word","term":"Messiah","o":["the anointed one","a costly perfume, precious spikenard","what the guests said it was worth"],"a":0},
      {"day":81,"kind":"fork","q":"you're Mary. after three days of searching, you find your twelve-year-old son in the temple, calmly talking with the teachers. what do you say?","o":["nothing. you just take him home.","son, why hast thou done so to us?","scold him in front of everyone."],"a":1},
    ] },
    { first: 97, last: 156, camp: "Camp 3", name: "The practices", qs: [
      {"day":108,"kind":"fork","q":"it's a Sunday in Year B, the year of Mark. but Mark's Gospel is short. what fills the gap?","o":["Mark is read twice.","John fills out the year.","the letters of Paul are read instead."],"a":1},
      {"day":127,"kind":"word","term":"chrismation","o":["the Eastern churches' name","olive oil and balsam","the anointed one"],"a":0},
      {"day":144,"kind":"fork","q":"it's early December. the stores are all Christmas. your parish is violet and quiet. what is Advent asking of you?","o":["start celebrating Christmas now.","wait, and prepare, before the feast.","skip December entirely."],"a":1},
    ] },
    { first: 157, last: 231, camp: "Camp 4", name: "The text", qs: [
      {"day":171,"kind":"fork","q":"you're King David. a prophet has just told you, thou art the man. you could have him thrown out, or worse. what do you do?","o":["deny it and send him away.","say, I have sinned against the Lord.","explain why it was not really your fault."],"a":1},
      {"day":194,"kind":"word","term":"Zebedee","o":["left in the boat with hired men","casting nets into the sea","mending nets in the boat"],"a":0},
      {"day":215,"kind":"fork","q":"you're Peter on the mountain. Jesus is shining, Moses and Elijah are there, and you're terrified. what do you say?","o":["let's build three tents and stay.","nothing at all.","let's go and tell everyone right now."],"a":0},
    ] },
    { first: 232, last: 331, camp: "Camp 5", name: "The depths", qs: [
      {"day":252,"kind":"fork","q":"you've reached the deepest peace with God you've ever known. what do you do with your days now?","o":["withdraw from everything and stay in prayer.","keep praying, and pour yourself into work and service.","tell everyone about your experiences."],"a":1},
      {"day":282,"kind":"word","term":"The Wisdom of the Desert","o":["Merton's book of their sayings","Greek: the desert","an early desert hermit in Egypt"],"a":0},
      {"day":312,"kind":"fork","q":"you're on the hillside in Galilee. Jesus sits down and begins to teach. who does he call blessed first?","o":["the rich and successful.","the poor in spirit.","the teachers of the law."],"a":1},
    ] },
    { first: 332, last: 441, camp: "Year 2", name: "Kings, prophets, wisdom and the seven books", qs: [
      {"day":354,"kind":"fork","q":"you're Esau, home from the field, exhausted. your brother has stew on the fire and says: sell me your birthright first. what does the story say you do?","o":["refuse and find food elsewhere.","swear it away, eat, drink, and go.","offer him money instead."],"a":1},
      {"day":387,"kind":"word","term":"Saturday Night Prayer","o":["where Catholics read these verses","Hebrew: hear","the scroll on the doorframe"],"a":0},
      {"day":419,"kind":"fork","q":"you're the prophet, sent to people who've lost their city and their Temple, and who know they brought some of it on themselves. how do you begin?","o":["with a list of what they did wrong.","with comfort, and the news their sin is forgiven.","with a plan to rebuild the walls."],"a":1},
    ] },
    { first: 442, last: 533, camp: "Year 2", name: "The Gospel of Luke", qs: [
      {"day":457,"kind":"fork","q":"you're Joanna, married to a steward in Herod's palace. a traveling preacher's group needs money to keep going. what do you do?","o":["stay out of it; your husband's job is at stake.","give from your own means and go with them.","send a small gift and stay home."],"a":1},
      {"day":488,"kind":"word","term":"Cleophas","o":["one of the two walking","their grief, in the past tense","the scriptures opened"],"a":0},
      {"day":515,"kind":"fork","q":"you're Philip. some Greeks visiting Jerusalem for the feast come to you and say, sir, we would see Jesus. what do you do?","o":["tell them he only speaks to Jews.","go and tell Andrew, and the two of you tell Jesus.","bring them straight into the crowd."],"a":1},
    ] },
    { first: 534, last: 607, camp: "Year 2", name: "The letters", qs: [
      {"day":549,"kind":"fork","q":"you're Lydia. you and your household have just been baptized by the river. what do you do?","o":["thank them and go home.","insist they come and stay at your house.","give them money for the journey."],"a":1},
      {"day":571,"kind":"word","term":"naos","o":["the inner sanctuary","a slave set free by payment","a Corinthian slogan"],"a":0},
      {"day":593,"kind":"fork","q":"you've just heard 'pray without ceasing' read aloud. what does the pilgrim in the old Russian story do?","o":["decide it's impossible and forget it.","set out walking to learn how.","pray only on Sundays to make up for it."],"a":1},
    ] },
    { first: 608, last: 696, camp: "Year 2", name: "The year of feasts and their readings", qs: [
      {"day":626,"kind":"fork","q":"you're John. an elder points at the crowd in white and asks you: who are these, and where did they come from? what do you say?","o":["these are the ones who never suffered.","my lord, thou knowest.","these are the twelve tribes."],"a":1},
      {"day":652,"kind":"word","term":"Deuteronomy","o":["where each answer comes from","the hungry man's test","throw yourself down"],"a":0},
      {"day":678,"kind":"fork","q":"you're Peter on the mountain. Jesus is shining, Moses and Elijah are there, and you're terrified. what do you say?","o":["nothing at all.","let's make three tents and stay.","let's go back down and tell everyone."],"a":1},
    ] },
    { first: 697, last: 796, camp: "Year 3", name: "The first Christians and the Fathers", qs: [
      {"day":717,"kind":"fork","q":"you're the emperor's mother, and you want to honor the places where Jesus lived. what do you do?","o":["send gold and a letter.","go yourself, pray there, and build churches.","build a church at home in Rome."],"a":1},
      {"day":747,"kind":"word","term":"Cogitosus","o":["wrote her life from what he heard","hung on a sunbeam","leads a community of nuns"],"a":0},
      {"day":779,"kind":"fork","q":"you're Gregory XII, the claimant in Rome. a council is gathering to end the split. what do you do?","o":["refuse to recognize the council at all.","let the council be called in your name, then resign.","flee the city before it can act."],"a":1},
    ] },
    { first: 797, last: 886, camp: "Year 3", name: "The middle ages", qs: [
      {"day":814,"kind":"fork","q":"you're Bonaventure, at the top of your map. a student asks what to study next to reach God. what do you tell him?","o":["read more books, harder ones.","ask for grace, not learning; desire, not understanding.","go back and look at creatures again."],"a":1},
      {"day":842,"kind":"word","term":"Romans 12","o":["reformed in the newness of your mind","Greek beside his own Latin","a farmer singing the Gospel"],"a":0},
      {"day":867,"kind":"fork","q":"you're Margaret Mary. you've told your superiors what you saw in the chapel, and they doubt you. what do you do?","o":["leave the convent and spread the message yourself.","stay, keep obeying, and open it to the confessor you're given.","decide you imagined it and never mention it again."],"a":1},
    ] },
    { first: 887, last: 971, camp: "Year 3", name: "The modern Church", qs: [
      {"day":904,"kind":"fork","q":"you're the pope. Catholics are fighting on both sides of a great war. what do you do?","o":["support the side with more Catholics.","say nothing and wait.","call it a useless slaughter and propose terms for peace."],"a":2},
      {"day":929,"kind":"word","term":"Pope Francis","o":["wrote to the whole Church","abusers moved, survivors doubted","kept telling their stories"],"a":0},
      {"day":954,"kind":"fork","q":"you're Chavara, newly given authority over the parishes. you want the faith to grow strong. what do you ask every parish to build?","o":["a bigger church tower.","a school beside the church.","a wall around the churchyard."],"a":1},
    ] },
    { first: 972, last: 1061, camp: "Year 3", name: "Saints across the calendar", qs: [
      {"day":991,"kind":"fork","q":"you live in Geel. strangers troubled in mind keep arriving to pray at the shrine, with nowhere to stay. what do you do?","o":["ask the town to turn them away.","take one of them into your home.","leave it to the shrine's keepers."],"a":1},
      {"day":1017,"kind":"word","term":"Bathsheba","o":["sat at the king's right hand","of his kingdom there shall be no end","the mother of my Lord"],"a":0},
      {"day":1045,"kind":"fork","q":"you're Anne. after a long wait you have a daughter, and you promised to give her back to God. what do you do?","o":["keep her home and forget the promise.","bring her to the Temple, as you promised.","promise again when she's grown."],"a":1},
    ] },
  ] },
  CHRISTIANITY: { lastWritten: 1061, stops: [
    { first: 1, last: 21, camp: "Camp 1", name: "First steps", qs: [
      {"day":4,"kind":"fork","q":"you're teaching people to pray, and you choose the first word they'll say to God. which does Jesus choose?","o":["king.","father.","judge."],"a":1},
      {"day":11,"kind":"word","term":"prodigal","o":["an old word for wasteful","asked for his share, and spent it","ran, and fell on his neck"],"a":0},
      {"day":19,"kind":"fork","q":"it's the night you know you'll be betrayed. twelve friends around one table at Passover. what do you do?","o":["give a long farewell speech about what to believe.","take bread, give thanks, break it, and say: remember me.","leave the city before anyone comes."],"a":1},
    ] },
    { first: 22, last: 96, camp: "Camp 2", name: "The stories", qs: [
      {"day":37,"kind":"fork","q":"you're Mary. an angel has just told you you'll have a son. what do you say first?","o":["nothing. you just say yes.","you ask how this can be.","you ask for a sign."],"a":1},
      {"day":59,"kind":"word","term":"Zacchaeus","o":["chief of the tax collectors, and rich","the tree he climbed","grumbled that he was a sinner"],"a":0},
      {"day":81,"kind":"fork","q":"you're Ananias. you've just laid your hands on the man who came to arrest you. what is your first word to him?","o":["Saul of Tarsus.","brother.","persecutor."],"a":1},
    ] },
    { first: 97, last: 156, camp: "Camp 3", name: "The practices", qs: [
      {"day":111,"kind":"fork","q":"it's December 27. the neighbors' tree is already on the curb. what does the church calendar say to do?","o":["pack it all away. Christmas is over.","keep celebrating, all the way to January 6.","start fasting for Lent."],"a":1},
      {"day":127,"kind":"word","term":"Mark","o":["sixteen chapters, a good start","searched the scriptures daily","a plan for the Bible in a year"],"a":0},
      {"day":145,"kind":"fork","q":"the earth shakes, the nations rage, the kingdoms totter. then God speaks. what does he say?","o":["fight harder.","be still, and know that I am God.","run for the mountains."],"a":1},
    ] },
    { first: 157, last: 231, camp: "Camp 4", name: "The text", qs: [
      {"day":170,"kind":"fork","q":"you're teaching in a packed house. a message comes in: your mother and brothers are outside. what does Jesus do?","o":["get up and go straight out to them.","look around at the circle and call them his family.","send word that he's too busy."],"a":1},
      {"day":194,"kind":"word","term":"Peter","o":["took him aside and rebuked him","an adversary, one in the way","Rome's execution"],"a":0},
      {"day":215,"kind":"fork","q":"you're told you'll one day stand before governors and kings because of your faith. what does Jesus tell you to do?","o":["prepare your defense carefully.","don't worry beforehand; say what is given you.","stay silent no matter what."],"a":1},
    ] },
    { first: 232, last: 331, camp: "Camp 5", name: "The depths", qs: [
      {"day":253,"kind":"fork","q":"you're on the hillside. Jesus has just said you can't serve God and money. your stomach says: then who pays for dinner? what does he point at?","o":["the birds overhead.","the disciples' purse.","the fields of wheat."],"a":0},
      {"day":281,"kind":"word","term":"Brother Lawrence","o":["God among the pots","all shall be well","a room further in"],"a":0},
      {"day":309,"kind":"fork","q":"Augsburg, 1999. after centuries of mutual condemnation, Catholics and Lutherans sit down at one table. what do they sign?","o":["a full merger of the two churches.","a declaration that on the heart of justification they agree.","a statement that the argument never mattered."],"a":1},
    ] },
    { first: 332, last: 411, camp: "Year 2", name: "Genesis", qs: [
      {"day":348,"kind":"fork","q":"you're seventy-five and settled. God says: leave your country, your kin, your father's house, for a land I'll show you. what do you do?","o":["ask for the name of the land first.","go.","send your nephew to check it out."],"a":1},
      {"day":372,"kind":"word","term":"Judah","o":["offered himself in Benjamin's place","the cup was found in his sack","searched oldest to youngest"],"a":0},
      {"day":397,"kind":"fork","q":"you're Aaron. Moses has been gone forty days, and a crowd says, make us gods. what do you do?","o":["tell them to wait for Moses.","ask for their gold earrings.","climb the mountain to find him."],"a":1},
    ] },
    { first: 412, last: 501, camp: "Year 2", name: "The Psalms and the wisdom books", qs: [
      {"day":431,"kind":"fork","q":"you've just told your soul to bless the Lord. what does the psalm do next?","o":["ask for a long list of things.","count, one by one, what has already been given.","apologize for not praying more."],"a":1},
      {"day":459,"kind":"word","term":"Tisha B'Av","o":["when Jews read Lamentations","five poems over a fallen city","fail not"],"a":0},
      {"day":483,"kind":"fork","q":"you're Peter. a crowd hears your friends speaking in other languages, and some laugh that you're all drunk. what do you do?","o":["slip away before it gets worse.","stand up and quote an old prophet.","argue about how much wine is too much."],"a":1},
    ] },
    { first: 502, last: 591, camp: "Year 2", name: "The Gospel of Luke, read through", qs: [
      {"day":519,"kind":"fork","q":"you're Simon. the nets are tearing, the boats are sinking, and you're looking at the man who told you where to fish. what do you do?","o":["haul in the fish and start counting.","fall at his knees: depart from me, I'm a sinful man.","ask him to come fishing every night."],"a":1},
      {"day":547,"kind":"word","term":"assarion","o":["the coin the KJV calls a farthing","sold for two farthings","all numbered"],"a":0},
      {"day":573,"kind":"fork","q":"you're asked: is it lawful to pay taxes to Caesar? yes angers the crowd, no angers Rome. what do you do?","o":["say yes, and keep Rome happy.","say no, and win the crowd.","ask whose picture is on the coin."],"a":2},
    ] },
    { first: 592, last: 696, camp: "Year 2", name: "The Gospel of John, read through", qs: [
      {"day":613,"kind":"fork","q":"you're an officer sent to arrest Jesus at the feast. you hear him teaching. what do you do?","o":["arrest him as ordered.","go back empty-handed.","join the crowd that wants to stone him."],"a":1},
      {"day":644,"kind":"word","term":"Francis Bacon","o":["jesting Pilate, who would not stay","goes out, in, and out again","is not of this world"],"a":0},
      {"day":673,"kind":"fork","q":"a neighbor with no coat and no food knocks on your door. you say, stay warm, eat something, and close the door. what does James ask?","o":["\"what doth it profit?\"","\"did you pray for them?\"","\"were they really in need?\""],"a":0},
    ] },
    { first: 697, last: 806, camp: "Year 3", name: "The early church", qs: [
      {"day":718,"kind":"fork","q":"you're David. the king who keeps trying to kill you is alone in the cave, his back to you. your men say: now. what do you do?","o":["kill him. it's self-defense.","cut a corner from his robe and let him go.","stay hidden and do nothing at all."],"a":1},
      {"day":752,"kind":"word","term":"Luke","o":["many have taken in hand","the beginning of the gospel","the world could not contain the books"],"a":0},
      {"day":783,"kind":"fork","q":"you lead a church that treasures the words one nature of God the Word made flesh. the council says two natures. what do you do?","o":["sign the wording anyway, to keep the peace.","keep your own wording: one united nature, from two.","stop saying anything about who Christ is."],"a":1},
    ] },
    { first: 807, last: 879, camp: "Year 3", name: "The middle centuries, east and west", qs: [
      {"day":821,"kind":"fork","q":"you're Thomas, the quiet student. a classmate who thinks you're slow offers to explain the lessons to you. what do you do?","o":["tell him you already understand them.","say yes, thank you, and listen.","ignore him."],"a":1},
      {"day":842,"kind":"word","term":"Rome","o":["tradition says Peter and Paul are buried","tradition places the tomb of James","where Thomas Becket was murdered"],"a":0},
      {"day":865,"kind":"fork","q":"you're helping write the plan for Scotland's new church. you want every Christian to read the Bible. what do you put in the plan?","o":["print more Bibles and hope.","a school in every parish, for rich and poor.","a university in the capital for future pastors."],"a":1},
    ] },
    { first: 880, last: 970, camp: "Year 3", name: "The modern church across the world", qs: [
      {"day":898,"kind":"fork","q":"you're a pastor and your town is swept by weeping, late-night prayer and fierce argument. some say it's God, some say it's hysteria. what do you do?","o":["shut it down to keep the peace.","think it through and test it by what it changes.","celebrate every strong feeling as proof."],"a":1},
      {"day":926,"kind":"word","term":"Afanasy","o":["the servant he struck, then bowed to","an elder in Dostoevsky's novel","his dying older brother"],"a":0},
      {"day":953,"kind":"fork","q":"you're Corrie, after a talk on forgiveness. a former guard from your camp walks up with his hand out. what happens?","o":["she walks away without a word.","she feels nothing, prays for help, and takes his hand.","she shakes it at once and feels only warmth."],"a":1},
    ] },
    { first: 971, last: 1061, camp: "Year 3", name: "A year of feasts and saints' days", qs: [
      {"day":988,"kind":"fork","q":"you're a priest-physicist, and church voices start saying your theory proves the Bible. what do you do?","o":["welcome it: the theory proves Genesis.","push back: physics can't prove or disprove God.","drop the theory to avoid trouble."],"a":1},
      {"day":1016,"kind":"word","term":"theophany","o":["God made visible","the Spirit of God descending","this is my beloved Son"],"a":0},
      {"day":1044,"kind":"fork","q":"you're John. your followers tell you the crowds have gone over to Jesus. what do you say?","o":["\"then we'll have to work harder.\"","\"he must increase, but I must decrease.\"","\"they'll come back.\""],"a":1},
    ] },
  ] },
};
